# Generated by Django 3.1.7 on 2021-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCurrencyFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=30)),
                ('currency_thousand_delimeter', models.CharField(default='.', max_length=2)),
                ('currency_decimal_delimeter', models.CharField(default=',', max_length=2)),
                ('currency_symbol_ubication', models.CharField(default='left', max_length=10)),
                ('bool_cents', models.BooleanField(default=False)),
            ],
        ),
    ]
