# Generated by Django 3.1.7 on 2021-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyformat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcurrencyformat',
            name='display_currency',
            field=models.CharField(default='symbol', max_length=10),
        ),
    ]
